local t = {
    ["rape"] = "rap̣e",
	["raped"] = "rap̣ed",
	["nigga"] = "ทigga",
	["nigger"] = "ทigger",
	["niggas"] = "ทiggas",
	["niggers"] = "ทiggers",
	["fuck"] = "fนck",
	["fucks"] = "fนcks",
	["shit"] = "ѕһı̇t",
	["Shit"] = "Sһı̇t",
	["SHIT"] = "ṢHIT",
	["Sexy"] = "Ṣexy",
	["SEXY"] = "ṢEXY",
	["Fuck"] = "Fนck",
	["Fucks"] = "Fนcks",
	["fucking"] = "fนcking",
	["Fucking"] = "Fนcking",
	["whore"] = "ẇhore",
	["whores"] = "ẇhores",
	["Whore"] = "̇Ẇhore",
	["Whores"] = "̇Ẇhores",
	["fucker"] = "fนcker",
	["Fucker"] = "Fนcker",
	["fuckers"] = "fนckers",
	["Fuckers"] = "Fนckers",
	["cum"] = "cนm",
	["CUM"] = "ĊUM",
	["ASS"] = "ẠSS",
	["meth"] = "ṁeth",
	["bitch"] = "bı̇tch",
	["Bitch"] = "Bı̇tch",
	["Hitler"] = "Hitӏer",
	["hitler"] = "һitӏer",
}

return t
