local t = {
    ["rape"] = "rap̣e",
	["raped"] = "rap̣ed",
	["Nigga"] = "Nı̇gga",
	["Nigger"] = "Nı̇gger",
	["fuck"] = "fนck",
	["fucks"] = "fนcks",
	["shit"] = "ѕһı̇t",
	["Shit"] = "Sһı̇t",
	["SHIT"] = "ṢHIT",
	["Fuck"] = "Fนck",
	["Fucks"] = "Fนcks",
	["fucking"] = "fนcking",
	["Fucking"] = "Fนcking",
	["whore"] = "ẇhore",
	["whores"] = "ẇhores",
	["Whore"] = "̇Ẇhore",
	["Whores"] = "̇Ẇhores",
	["fucker"] = "fนcker",
	["Fucker"] = "Fนcker",
	["fuckers"] = "fนckers",
	["Fuckers"] = "Fนckers",
}

return t
