local t = {
    ["rape"] = "rap̣e",
	["raped"] = "rap̣ed",
	["Nigga"] = "Nı̇gga",
	["Nigger"] = "Nı̇gger",
	["Niggas"] = "Nı̇ggas",
	["Niggers"] = "Nı̇ggers",
	["fuck"] = "fนck",
	["fucks"] = "fนcks",
	["shit"] = "ѕһı̇t",
	["Shit"] = "Sһı̇t",
	["SHIT"] = "ṢHIT",
	["Sexy"] = "Ṣexy",
	["SEXY"] = "ṢEXY",
	["Fuck"] = "Fนck",
	["Fucks"] = "Fนcks",
	["fucking"] = "fนcking",
	["Fucking"] = "Fนcking",
	["whore"] = "ẇhore",
	["whores"] = "ẇhores",
	["Whore"] = "̇Ẇhore",
	["SUCK"] = "Sᴜᴄᴋ",
	["Whores"] = "̇Ẇhores",
	["fucker"] = "fนcker",
	["Fucker"] = "Fนcker",
	["fuckers"] = "fนckers",
	["Fuckers"] = "Fนckers",
	["cum"] = "cนm",
	["CUM"] = "ÇUM",
	["autistic"] = "aนtistic",
	["Autistic"] = "Aนtistic",
	["retard"] = "ṛetard",
	["ASS"] = "ẠSS",
	["asshole"] = "ȧѕѕhole",
	["Asshole"] = "Ạsshole",
	["Ass"] = "Ạѕѕ",
	["meth"] = "ṁeth",
	["bitch"] = "bı̇tch",
	["Bitch"] = "Bı̇tch",
	["Hitler"] = "Hitӏer",
	["hitler"] = "һitӏer",
}


return t
